# Generated by Django 4.2.4 on 2023-08-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoorStatusHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='close', max_length=250)),
                ('status_id', models.IntegerField(default=1)),
                ('updated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=1)),
                ('distance', models.IntegerField(default=1)),
                ('status', models.CharField(default='off', max_length=25)),
                ('latitude', models.DecimalField(decimal_places=7, default='37.5566056', max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=7, default='-122.0287363', max_digits=20)),
                ('battery', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, unique=True)),
                ('brief', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='OFF', max_length=200)),
                ('battery', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_address', models.CharField(default='36039 Pizarro dr, Fremont, Ca, 94653', max_length=200)),
                ('departure_latitude', models.DecimalField(decimal_places=7, default='37.5566056', max_digits=20)),
                ('departure_longitude', models.DecimalField(decimal_places=7, default='-122.0287363', max_digits=20)),
                ('landing_address', models.CharField(default='35820 Fremont Blvd, Fremont, CA 94536', max_length=200)),
                ('landing_latitude', models.DecimalField(decimal_places=7, default='37.5605321', max_digits=20)),
                ('landing_longitude', models.DecimalField(decimal_places=7, default='-122.0180234', max_digits=20)),
                ('order_description', models.TextField(default='no description')),
                ('description', models.TextField(default='no description')),
                ('weight', models.IntegerField(default=10)),
                ('trigger', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=250)),
                ('status_id', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=250)),
                ('updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='coming_to_door', max_length=250)),
                ('status_id', models.IntegerField(default='1')),
                ('comment', models.TextField(default='no comment')),
                ('updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageStatusHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='coming_to_door', max_length=250)),
                ('status_id', models.IntegerField(default='1')),
                ('updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDoorPickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='36039 Pizarro dr, Fremont, Ca, 94653', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, default='37.5566056', max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=7, default='-122.0287363', max_digits=20)),
                ('order_description', models.TextField(default='no description')),
                ('description', models.TextField(default='no description')),
                ('madel', models.CharField(default='small_door_aaa_001', max_length=200)),
                ('square', models.CharField(default='20x20', max_length=200)),
                ('cube_size', models.CharField(default='20x20x20', max_length=200)),
                ('trigger', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='open', max_length=250)),
                ('status_id', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SystemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=250, unique=True)),
                ('brief', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=250)),
                ('status_id', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='no description')),
                ('comment', models.TextField(default='no comment')),
                ('updated_from', models.CharField(default='programmer', max_length=200)),
                ('order_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.order')),
            ],
        ),
        migrations.CreateModel(
            name='DoorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', max_length=250)),
                ('status_id', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='no description')),
                ('comment', models.TextField(default='no comment')),
                ('updated_from', models.CharField(default='programmer', max_length=200)),
                ('order_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.storedoorpickup')),
            ],
        ),
    ]
