# Generated by Django 4.2.4 on 2023-08-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='status_battery',
            field=models.CharField(default='charging', max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status_fly',
            field=models.CharField(default='waiting', max_length=25),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status_order',
            field=models.CharField(default='waiting', max_length=25),
        ),
    ]
